---
- name: update cache (yum)
  when:
    - ansible_os_family == 'RedHat'
  yum:
    update_cache: yes

- name: update cache (apt)
  when:
    - ansible_os_family == 'Debian'
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: install build tools
  include_role:
    name: robertdebock.buildtools

- name: check if git is installed
  command: "git --version"
  register: git_installed
  ignore_errors: yes
  # bypass idempotence check
  changed_when: false

- name: install git
  when: git_installed.rc != 0
  package:
    name: git
    state: present

- name: clone git repo
  git:
    repo: https://github.com/tsibley/FastTree
    dest: /opt/FastTree

- name: run make
  # bypass idempotence check
  changed_when: false
  make:
    chdir: /opt/FastTree
    target: FastTreeDblMP

- name: create link
  file:
    src: "/opt/FastTree/FastTreeDblMP"
    dest: "/usr/bin/FastTreeDblMP"
    state: link    
